# .github/sync-to-Analyzer.yml
group:
  - files:
      - source: data/reports/raw_yahoo_finance.csv
        dest:   data/stage1_raw/raw_yahoo_finance.csv
      - source: raw_column_definition.md
        dest:   definitions/raw_column_definition_YahooFinance.md
    repos: |
      wenchiehlee-investment/Python-Actions.GoodInfo.Analyzer
